query category(
  $categoryId: Float
  $slug: String
  $hidden: YesNo
  $language: String
  $priceCalculateProductInput: PriceCalculateProductInput
  $categoryProductSearchInput: CategoryProductSearchInput
  $imageSearchFilters: MediaImageProductSearchInput
  $imageVariantFilters: TransformationsInput!
  $filterAvailableAttributeInput: FilterAvailableAttributeInput
  $attributeResultSearchInput: AttributeResultSearchInput
) {
  category(categoryId: $categoryId, slug: $slug, hidden: $hidden) {
    ...CategoryFields
  }
}