/**
 * @enum CategoryFieldName
 Fields available for Category mapping
 */
export enum CategoryFieldName {
  PARENT_SOURCE_ID = "PARENT_SOURCE_ID",
  PARENT_SOURCE_NAME = "PARENT_SOURCE_NAME",
  PARENT_ID = "PARENT_ID",
  DEFAULT_LANGUAGE = "DEFAULT_LANGUAGE",
  LANGUAGE = "LANGUAGE",
  NAME = "NAME",
  DESCRIPTION = "DESCRIPTION",
  SHORT_DESCRIPTION = "SHORT_DESCRIPTION",
  METADATA_TITLE = "METADATA_TITLE",
  METADATA_DESCRIPTION = "METADATA_DESCRIPTION",
  METADATA_KEYWORDS = "METADATA_KEYWORDS",
  METADATA_CANONICAL_URL = "METADATA_CANONICAL_URL",
  SOURCE_NAME = "SOURCE_NAME",
  SOURCE_ID = "SOURCE_ID",
  ID = "ID",
  HIDDEN = "HIDDEN",
}