/**
 * @enum ClusterFieldName
 Fields available for Cluster mapping
 */
export enum ClusterFieldName {
  LANGUAGE = "LANGUAGE",
  NAMES = "NAMES",
  DESCRIPTIONS = "DESCRIPTIONS",
  SHORT_DESCRIPTIONS = "SHORT_DESCRIPTIONS",
  CODE = "CODE",
  CLUSTER_CONFIG_ID = "CLUSTER_CONFIG_ID",
  CLUSTER_ID = "CLUSTER_ID",
  SOURCE_NAME = "SOURCE_NAME",
  SOURCE_ID = "SOURCE_ID",
  CATEGORY_ID = "CATEGORY_ID",
  CATEGORY_SOURCE_NAME = "CATEGORY_SOURCE_NAME",
  CATEGORY_SOURCE_ID = "CATEGORY_SOURCE_ID",
  METADATA_TITLE = "METADATA_TITLE",
  METADATA_DESCRIPTION = "METADATA_DESCRIPTION",
  METADATA_KEYWORDS = "METADATA_KEYWORDS",
  METADATA_CANONICAL_URL = "METADATA_CANONICAL_URL",
  HIDDEN = "HIDDEN",
}