/**
 * @enum CompanyTermField
 Enumeration for CompanyTermField values
 */
export enum CompanyTermField {
  COMPANY_ID = "COMPANY_ID",
  COMPANY_NAME = "COMPANY_NAME",
  COMPANY_TAX_NUMBER = "COMPANY_TAX_NUMBER",
  COMPANY_COC_NUMBER = "COMPANY_COC_NUMBER",
  COMPANY_NOTES = "COMPANY_NOTES",
  COMPANY_DEBTOR_ID = "COMPANY_DEBTOR_ID",
  COMPANY_EMAIL = "COMPANY_EMAIL",
  COMPANY_ADDRESS_ID = "COMPANY_ADDRESS_ID",
  COMPANY_ADDRESS_FIRST_NAME = "COMPANY_ADDRESS_FIRST_NAME",
  COMPANY_ADDRESS_LAST_NAME = "COMPANY_ADDRESS_LAST_NAME",
  COMPANY_ADDRESS_STREET = "COMPANY_ADDRESS_STREET",
  COMPANY_ADDRESS_NUMBER = "COMPANY_ADDRESS_NUMBER",
  COMPANY_ADDRESS_NUMBER_EXTENSION = "COMPANY_ADDRESS_NUMBER_EXTENSION",
  COMPANY_ADDRESS_POSTAL_CODE = "COMPANY_ADDRESS_POSTAL_CODE",
  COMPANY_ADDRESS_CITY = "COMPANY_ADDRESS_CITY",
  COMPANY_ADDRESS_PHONE = "COMPANY_ADDRESS_PHONE",
  COMPANY_ADDRESS_MOBILE = "COMPANY_ADDRESS_MOBILE",
  COMPANY_ADDRESS_EMAIL = "COMPANY_ADDRESS_EMAIL",
  COMPANY_ADDRESS_CODE = "COMPANY_ADDRESS_CODE",
  CONTACT_ID = "CONTACT_ID",
  CONTACT_FIRST_NAME = "CONTACT_FIRST_NAME",
  CONTACT_LAST_NAME = "CONTACT_LAST_NAME",
  CONTACT_PHONE = "CONTACT_PHONE",
  CONTACT_MOBILE = "CONTACT_MOBILE",
  CONTACT_EMAIL = "CONTACT_EMAIL",
}
