/**
 * @enum ContactFieldName
 Fields available for Contact mapping
 */
export enum ContactFieldName {
  ABBREVIATION = "ABBREVIATION",
  DATE_OF_BIRTH = "DATE_OF_BIRTH",
  EMAIL = "EMAIL",
  FIRST_NAME = "FIRST_NAME",
  GENDER = "GENDER",
  CONTACT_ID = "CONTACT_ID",
  LANGUAGE = "LANGUAGE",
  LAST_NAME = "LAST_NAME",
  MIDDLE_NAME = "MIDDLE_NAME",
  MOBILE = "MOBILE",
  COMPANY_ID = "COMPANY_ID",
  PHONE = "PHONE",
  PRIMARY_LANGUAGE = "PRIMARY_LANGUAGE",
  TITLE = "TITLE",
  SOURCE_NAME = "SOURCE_NAME",
  SOURCE_ID = "SOURCE_ID",
  COMPANY_SOURCE_NAME = "COMPANY_SOURCE_NAME",
  COMPANY_SOURCE_ID = "COMPANY_SOURCE_ID",
  MAILING_LIST = "MAILING_LIST",
}