/**
 * @enum CustomerFieldName
 Fields available for Customer mapping
 */
export enum CustomerFieldName {
  DEBTOR_ID = "DEBTOR_ID",
  FIRST_NAME = "FIRST_NAME",
  MIDDLE_NAME = "MIDDLE_NAME",
  LAST_NAME = "LAST_NAME",
  ABBREVIATION = "ABBREVIATION",
  TITLE = "TITLE",
  DATE_OF_BIRTH = "DATE_OF_BIRTH",
  GENDER = "GENDER",
  SSN = "SSN",
  PHONE = "PHONE",
  EMAIL = "EMAIL",
  PRIMARY_LANGUAGE = "PRIMARY_LANGUAGE",
  CUSTOMER_ID = "CUSTOMER_ID",
  USERGROUP_ID = "USERGROUP_ID",
  SOURCE_NAME = "SOURCE_NAME",
  SOURCE_ID = "SOURCE_ID",
  USERGROUP_SOURCE_NAME = "USERGROUP_SOURCE_NAME",
  USERGROUP_SOURCE_ID = "USERGROUP_SOURCE_ID",
  LANGUAGE = "LANGUAGE",
}