/**
 * @enum CustomerTermField
 Enumeration for CustomerTermField values
 */
export enum CustomerTermField {
  CUSTOMER_ID = "CUSTOMER_ID",
  CUSTOMER_FIRST_NAME = "CUSTOMER_FIRST_NAME",
  CUSTOMER_LAST_NAME = "CUSTOMER_LAST_NAME",
  CUSTOMER_PHONE = "CUSTOMER_PHONE",
  CUSTOMER_MOBILE = "CUSTOMER_MOBILE",
  CUSTOMER_EMAIL = "CUSTOMER_EMAIL",
  CUSTOMER_DEBTOR_ID = "CUSTOMER_DEBTOR_ID",
  CUSTOMER_ADDRESS_ID = "CUSTOMER_ADDRESS_ID",
  CUSTOMER_ADDRESS_FIRST_NAME = "CUSTOMER_ADDRESS_FIRST_NAME",
  CUSTOMER_ADDRESS_LAST_NAME = "CUSTOMER_ADDRESS_LAST_NAME",
  CUSTOMER_ADDRESS_STREET = "CUSTOMER_ADDRESS_STREET",
  CUSTOMER_ADDRESS_NUMBER = "CUSTOMER_ADDRESS_NUMBER",
  CUSTOMER_ADDRESS_NUMBER_EXTENSION = "CUSTOMER_ADDRESS_NUMBER_EXTENSION",
  CUSTOMER_ADDRESS_POSTAL_CODE = "CUSTOMER_ADDRESS_POSTAL_CODE",
  CUSTOMER_ADDRESS_CITY = "CUSTOMER_ADDRESS_CITY",
  CUSTOMER_ADDRESS_PHONE = "CUSTOMER_ADDRESS_PHONE",
  CUSTOMER_ADDRESS_MOBILE = "CUSTOMER_ADDRESS_MOBILE",
  CUSTOMER_ADDRESS_EMAIL = "CUSTOMER_ADDRESS_EMAIL",
  CUSTOMER_ADDRESS_CODE = "CUSTOMER_ADDRESS_CODE",
}
