/**
 * @enum DiscountSortField
 Fields available for sorting Discount records
 */
export enum DiscountSortField {
  ID = "ID",
  PRICESHEETID = "PRICESHEETID",
  PRODUCTID = "PRODUCTID",
  CATEGORYID = "CATEGORYID",
  PRICEGROUP = "PRICEGROUP",
  VALUE = "VALUE",
  DISCOUNTTYPE = "DISCOUNTTYPE",
  QUANTITYFROM = "QUANTITYFROM",
  VALIDFROM = "VALIDFROM",
  VALIDTO = "VALIDTO",
  LAST_MODIFIED_AT = "LAST_MODIFIED_AT",
  CREATED_AT = "CREATED_AT",
}