/**
 * @enum DocumentFieldName
 Fields available for Document mapping
 */
export enum DocumentFieldName {
  ID = "ID",
  LANGUAGE = "LANGUAGE",
  ALT_VALUE = "ALT_VALUE",
  DESCRIPTION_VALUE = "DESCRIPTION_VALUE",
  TAGS_VALUES = "TAGS_VALUES",
  DOCUMENT_FILE_URI = "DOCUMENT_FILE_URI",
  DOCUMENT_FILE_NAME = "DOCUMENT_FILE_NAME",
  PRIORITY = "PRIORITY",
  PRODUCT_ID = "PRODUCT_ID",
  CLUSTER_ID = "CLUSTER_ID",
  CATEGORY_ID = "CATEGORY_ID",
  SPAREPARTS_MACHINE_ID = "SPAREPARTS_MACHINE_ID",
}