/**
 * @enum EmailEventType
 Enumeration for EmailEventType values
 */
export enum EmailEventType {
  ORDER_PLACED = "ORDER_PLACED",
  ORDER_CONFIRMED = "ORDER_CONFIRMED",
  ORDER_SHIPPED = "ORDER_SHIPPED",
  ORDER_DELIVERED = "ORDER_DELIVERED",
  PASSWORD_RESET = "PASSWORD_RESET",
  WELCOME = "WELCOME",
  NEWSLETTER = "NEWSLETTER"
}