 /**
 * @enum EventTrigger
 Enumeration for EventTrigger values
 */
export enum EventTrigger {
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_UPDATED = "ORDER_UPDATED",
  ORDER_CANCELLED = "ORDER_CANCELLED",
  CUSTOMER_REGISTERED = "CUSTOMER_REGISTERED",
  CART_ABANDONED = "CART_ABANDONED",
  PAYMENT_COMPLETED = "PAYMENT_COMPLETED",
  PRODUCT_VIEWED = "PRODUCT_VIEWED"
}