/**
 * @enum ImageFieldName
 Fields available for Image mapping
 */
export enum ImageFieldName {
  ID = "ID",
  LANGUAGE = "LANGUAGE",
  ALT_VALUE = "ALT_VALUE",
  DESCRIPTION_VALUE = "DESCRIPTION_VALUE",
  TAGS_VALUES = "TAGS_VALUES",
  IMAGE_FILE_URI = "IMAGE_FILE_URI",
  IMAGE_FILE_NAME = "IMAGE_FILE_NAME",
  PRIORITY = "PRIORITY",
  PRODUCT_ID = "PRODUCT_ID",
  CLUSTER_ID = "CLUSTER_ID",
  CATEGORY_ID = "CATEGORY_ID",
  SPAREPARTS_MACHINE_ID = "SPAREPARTS_MACHINE_ID",
}