/**
 * @enum InventoryFieldName
 Fields available for Inventory mapping
 */
export enum InventoryFieldName {
  LOOKUP_KEY = "LOOKUP_KEY",
  INVENTORY_TYPE = "INVENTORY_TYPE",
  QUANTITY = "QUANTITY",
  SKU = "SKU",
  SUPPLIER_CODE = "SUPPLIER_CODE",
  SUPPLIER = "SUPPLIER",
  PRODUCT_ID = "PRODUCT_ID",
  SOURCE_ID = "SOURCE_ID",
  SOURCE_NAME = "SOURCE_NAME",
  LANGUAGE = "LANGUAGE",
  WAREHOUSE_ID = "WAREHOUSE_ID",
  COMPANY_ID = "COMPANY_ID",
  COMPANY_SOURCE_ID = "COMPANY_SOURCE_ID",
  COMPANY_SOURCE_NAME = "COMPANY_SOURCE_NAME",
  COMPANY_LANGUAGE = "COMPANY_LANGUAGE",
  USERGROUP_ID = "USERGROUP_ID",
  USERGROUP_SOURCE_ID = "USERGROUP_SOURCE_ID",
  USERGROUP_SOURCE_NAME = "USERGROUP_SOURCE_NAME",
  USERGROUP_LANGUAGE = "USERGROUP_LANGUAGE",
  LOCATION = "LOCATION",
  COST_PRICE = "COST_PRICE",
  NEXT_DELIVERY_DATE = "NEXT_DELIVERY_DATE",
  NOTES = "NOTES",
}