/**
 * @enum OrderSearchFields
 Enumeration for OrderSearchFields values
 */
export enum OrderSearchFields {
  ID = "ID",
  ACCOUNTING_ID = "ACCOUNTING_ID",
  DEBTOR_ID = "DEBTOR_ID",
  EXTERNAL_ORDER_ID = "EXTERNAL_ORDER_ID",
  EXTRA3 = "EXTRA3",
  EXTRA4 = "EXTRA4",
  INVOICE_ADDRESS_COMPANY = "INVOICE_ADDRESS_COMPANY",
  INVOICE_ADDRESS_FIRST_NAME = "INVOICE_ADDRESS_FIRST_NAME",
  INVOICE_ADDRESS_LAST_NAME = "INVOICE_ADDRESS_LAST_NAME",
  RECIPIENT_COMPANY = "RECIPIENT_COMPANY",
  RECIPIENT_EMAIL = "RECIPIENT_EMAIL",
  RECIPIENT_FIRST_NAME = "RECIPIENT_FIRST_NAME",
  RECIPIENT_LAST_NAME = "RECIPIENT_LAST_NAME",
  REFERENCE = "REFERENCE",
  REMARKS = "REMARKS",
  ITEM_EAN_CODE = "ITEM_EAN_CODE",
  ITEM_MANUFACTURER = "ITEM_MANUFACTURER",
  ITEM_MANUFACTURER_CODE = "ITEM_MANUFACTURER_CODE",
  ITEM_NAME = "ITEM_NAME",
  ITEM_NOTES = "ITEM_NOTES",
  ITEM_SKU = "ITEM_SKU",
  ITEM_SUPPLIER = "ITEM_SUPPLIER",
  ITEM_SUPPLIER_CODE = "ITEM_SUPPLIER_CODE",
}