import { AttributeDescriptionClass } from '../enum/AttributeDescriptionClass';
import { AttributeType } from '../enum/AttributeType';
import { LocalizedString } from './LocalizedString';
import { AttributeValue } from './AttributeValue';
/**
 Object class for AttributeDescription
 */
export interface AttributeDescription {
  /** Autogenerated ID of the AttributeDescription */
  id: string;
  /** Descriptive identifier for this AttributeDescription */
  name: string;
  /** The human readable description of the attribute's name.
        This is a language specific value. */
  descriptions: LocalizedString[];
  /** Attribute unit per language */
  units?: LocalizedString[];
  /** The class for this attribute. One of: [PRODUCT, CATEGORY, CLUSTER, CUSTOMER, CONTACT, COMPANY] */
  attributeClass: AttributeDescriptionClass;
  /** The type of the attribute. One of: [PRODUCT, CATEGORY, CLUSTER, CUSTOMER, CONTACT, COMPANY] */
  type: AttributeType;
  /** The ID of the connected valueset to use when type is ENUM */
  valuesetId?: number;
  /** The group this attribute belongs to, generally linked to a valueset. */
  group?: string;
  /** Flags whether this attribute should be used when generating
        catalog page filters */
  isSearchable: boolean;
  /** Flags whether this attribute should be used when generating
    product specifications. */
  isPublic: boolean;
  /** When true, only admin users can access the attribute and its values */
  isSystem: boolean;
  /** Flags whether this attribute is hidden and should
        only be used for background  operations. */
  isHidden: boolean;
  /** Attribute description creation date */
  createdAt: string;
  /** Attribute description last modified date */
  lastModifiedAt: string;
  /** The ID of the user that created the attribute description */
  createdBy?: number;
  /** The ID of the user that last modified the attribute description */
  lastModifiedBy?: number;
  /** The default value for this attribute */
  defaultValue: AttributeValue;
}