import { AttributeDescriptionClass } from '../enum/AttributeDescriptionClass';
import { AttributeType } from '../enum/AttributeType';
import { LocalizedString } from './LocalizedString';
import { AttributeValue } from './AttributeValue';
/**
 Object class for AttributeDescription
 */
export class AttributeDescription {
  /** Autogenerated ID of the AttributeDescription */
  id!: string;
  /** Descriptive identifier for this AttributeDescription */
  name!: string;
  /** The human readable description of the attribute's name.
        This is a language specific value. */
  descriptions!: LocalizedString[];
  /** Attribute unit per language */
  units?: LocalizedString[];
  /** The class for this attribute. One of: [PRODUCT, CATEGORY, CLUSTER, CUSTOMER, CONTACT, COMPANY] */
  attributeClass!: AttributeDescriptionClass;
  /** The type of the attribute. One of: [PRODUCT, CATEGORY, CLUSTER, CUSTOMER, CONTACT, COMPANY] */
  type!: AttributeType;
  /** The ID of the connected valueset to use when type is ENUM */
  valuesetId?: number;
  /** The group this attribute belongs to, generally linked to a valueset. */
  group?: string;
  /** Flags whether this attribute should be used when generating
        catalog page filters */
  isSearchable!: boolean;
  /** Flags whether this attribute should be used when generating
    product specifications. */
  isPublic!: boolean;
  /** When true, only admin users can access the attribute and its values */
  isSystem!: boolean;
  /** Flags whether this attribute is hidden and should
        only be used for background  operations. */
  isHidden!: boolean;
  /** Attribute description creation date */
  createdAt!: string;
  /** Attribute description last modified date */
  lastModifiedAt!: string;
  /** The ID of the user that created the attribute description */
  createdBy?: number;
  /** The ID of the user that last modified the attribute description */
  lastModifiedBy?: number;
  /** The default value for this attribute */
  defaultValue!: AttributeValue;
  constructor(data: Partial<AttributeDescription> = {}) {
    Object.assign(this, data);
  }

  /** Returns `id`. */
  getId(): string {
    return this.id;
  }
  /** Returns `name`. */
  getName(): string {
    return this.name;
  }
  /** Returns the description for the given language, falling back to NL. */
  getDescription(language: string = 'NL'): string | undefined {
    const arr = this.descriptions;
    if (!arr || arr.length === 0) return undefined;
    const entry = arr.find(e => e.language === language) ?? arr.find(e => e.language === 'NL');
    return entry?.value;
  }
  /** Returns the unit for the given language, falling back to NL. */
  getUnit(language: string = 'NL'): string | undefined {
    const arr = this.units;
    if (!arr || arr.length === 0) return undefined;
    const entry = arr.find(e => e.language === language) ?? arr.find(e => e.language === 'NL');
    return entry?.value;
  }
  /** Returns `attributeClass`. */
  getAttributeClass(): AttributeDescriptionClass {
    return this.attributeClass;
  }
  /** Returns `type`. */
  getType(): AttributeType {
    return this.type;
  }
  /** Returns `valuesetId`. */
  getValuesetId(): number | undefined {
    return this.valuesetId;
  }
  /** Returns `group`. */
  getGroup(): string | undefined {
    return this.group;
  }
  /** Returns `isSearchable`. */
  getIsSearchable(): boolean {
    return this.isSearchable;
  }
  /** Returns `isPublic`. */
  getIsPublic(): boolean {
    return this.isPublic;
  }
  /** Returns `isSystem`. */
  getIsSystem(): boolean {
    return this.isSystem;
  }
  /** Returns `isHidden`. */
  getIsHidden(): boolean {
    return this.isHidden;
  }
  /** Returns `createdAt`. */
  getCreatedAt(): string {
    return this.createdAt;
  }
  /** Returns `lastModifiedAt`. */
  getLastModifiedAt(): string {
    return this.lastModifiedAt;
  }
  /** Returns `createdBy`. */
  getCreatedBy(): number | undefined {
    return this.createdBy;
  }
  /** Returns `lastModifiedBy`. */
  getLastModifiedBy(): number | undefined {
    return this.lastModifiedBy;
  }
  /** Returns `defaultValue`. */
  getDefaultValue(): AttributeValue {
    return this.defaultValue;
  }
}