import { AttributeDescriptionClass } from '../enum/AttributeDescriptionClass';
import { AttributeType } from '../enum/AttributeType';
import { LocalizedString } from './LocalizedString';
import { AttributeValue } from './AttributeValue';
/**
 Object class for AttributeDescription
 */
export class AttributeDescription {
  /** Autogenerated ID of the AttributeDescription */
  private _id: string;
  /** Descriptive identifier for this AttributeDescription */
  private _name: string;
  /** The human readable description of the attribute's name.
        This is a language specific value. */
  private _descriptions: LocalizedString[];
  /** Attribute unit per language */
  private _units?: LocalizedString[];
  /** The class for this attribute. One of: [PRODUCT, CATEGORY, CLUSTER, CUSTOMER, CONTACT, COMPANY] */
  private _attributeClass: AttributeDescriptionClass;
  /** The type of the attribute. One of: [PRODUCT, CATEGORY, CLUSTER, CUSTOMER, CONTACT, COMPANY] */
  private _type: AttributeType;
  /** The ID of the connected valueset to use when type is ENUM */
  private _valuesetId?: number;
  /** The group this attribute belongs to, generally linked to a valueset. */
  private _group?: string;
  /** Flags whether this attribute should be used when generating
        catalog page filters */
  private _isSearchable: boolean;
  /** Flags whether this attribute should be used when generating
    product specifications. */
  private _isPublic: boolean;
  /** When true, only admin users can access the attribute and its values */
  private _isSystem: boolean;
  /** Flags whether this attribute is hidden and should
        only be used for background  operations. */
  private _isHidden: boolean;
  /** Attribute description creation date */
  private _createdAt: string;
  /** Attribute description last modified date */
  private _lastModifiedAt: string;
  /** The ID of the user that created the attribute description */
  private _createdBy?: number;
  /** The ID of the user that last modified the attribute description */
  private _lastModifiedBy?: number;
  /** The default value for this attribute */
  private _defaultValue: AttributeValue;
  /**
   Creates a new instance of AttributeDescription
   */
  constructor(data: Partial<AttributeDescription> = {}) {
    this._id = data.id!;
    this._name = data.name!;
    this._descriptions = data.descriptions!;
    this._units = data.units;
    this._attributeClass = data.attributeClass!;
    this._type = data.type!;
    this._valuesetId = data.valuesetId;
    this._group = data.group;
    this._isSearchable = data.isSearchable!;
    this._isPublic = data.isPublic!;
    this._isSystem = data.isSystem!;
    this._isHidden = data.isHidden!;
    this._createdAt = data.createdAt!;
    this._lastModifiedAt = data.lastModifiedAt!;
    this._createdBy = data.createdBy;
    this._lastModifiedBy = data.lastModifiedBy;
    this._defaultValue = data.defaultValue!;
  }
  /**
   Autogenerated ID of the AttributeDescription
   */
  get id(): string {
    return this._id;
  }
  /**
   Autogenerated ID of the AttributeDescription
   */
  set id(value: string) {
    this._id = value;
  }
  /**
   Descriptive identifier for this AttributeDescription
   */
  get name(): string {
    return this._name;
  }
  /**
   Descriptive identifier for this AttributeDescription
   */
  set name(value: string) {
    this._name = value;
  }
  /**
   The human readable description of the attribute's name.
        This is a language specific value.
   */
  get descriptions(): LocalizedString[] {
    return this._descriptions;
  }
  /**
   The human readable description of the attribute's name.
        This is a language specific value.
   */
  set descriptions(value: LocalizedString[]) {
    this._descriptions = value;
  }
  /**
   Attribute unit per language
   */
  get units(): LocalizedString[] | undefined {
    return this._units;
  }
  /**
   Attribute unit per language
   */
  set units(value: LocalizedString[] | undefined) {
    this._units = value;
  }
  /**
   The class for this attribute. One of: [PRODUCT, CATEGORY, CLUSTER, CUSTOMER, CONTACT, COMPANY]
   */
  get attributeClass(): AttributeDescriptionClass {
    return this._attributeClass;
  }
  /**
   The class for this attribute. One of: [PRODUCT, CATEGORY, CLUSTER, CUSTOMER, CONTACT, COMPANY]
   */
  set attributeClass(value: AttributeDescriptionClass) {
    this._attributeClass = value;
  }
  /**
   The type of the attribute. One of: [PRODUCT, CATEGORY, CLUSTER, CUSTOMER, CONTACT, COMPANY]
   */
  get type(): AttributeType {
    return this._type;
  }
  /**
   The type of the attribute. One of: [PRODUCT, CATEGORY, CLUSTER, CUSTOMER, CONTACT, COMPANY]
   */
  set type(value: AttributeType) {
    this._type = value;
  }
  /**
   The ID of the connected valueset to use when type is ENUM
   */
  get valuesetId(): number | undefined {
    return this._valuesetId;
  }
  /**
   The ID of the connected valueset to use when type is ENUM
   */
  set valuesetId(value: number | undefined) {
    this._valuesetId = value;
  }
  /**
   The group this attribute belongs to, generally linked to a valueset.
   */
  get group(): string | undefined {
    return this._group;
  }
  /**
   The group this attribute belongs to, generally linked to a valueset.
   */
  set group(value: string | undefined) {
    this._group = value;
  }
  /**
   Flags whether this attribute should be used when generating
        catalog page filters
   */
  get isSearchable(): boolean {
    return this._isSearchable;
  }
  /**
   Flags whether this attribute should be used when generating
        catalog page filters
   */
  set isSearchable(value: boolean) {
    this._isSearchable = value;
  }
  /**
   Flags whether this attribute should be used when generating
    product specifications.
   */
  get isPublic(): boolean {
    return this._isPublic;
  }
  /**
   Flags whether this attribute should be used when generating
    product specifications.
   */
  set isPublic(value: boolean) {
    this._isPublic = value;
  }
  /**
   When true, only admin users can access the attribute and its values
   */
  get isSystem(): boolean {
    return this._isSystem;
  }
  /**
   When true, only admin users can access the attribute and its values
   */
  set isSystem(value: boolean) {
    this._isSystem = value;
  }
  /**
   Flags whether this attribute is hidden and should
        only be used for background  operations.
   */
  get isHidden(): boolean {
    return this._isHidden;
  }
  /**
   Flags whether this attribute is hidden and should
        only be used for background  operations.
   */
  set isHidden(value: boolean) {
    this._isHidden = value;
  }
  /**
   Attribute description creation date
   */
  get createdAt(): string {
    return this._createdAt;
  }
  /**
   Attribute description creation date
   */
  set createdAt(value: string) {
    this._createdAt = value;
  }
  /**
   Attribute description last modified date
   */
  get lastModifiedAt(): string {
    return this._lastModifiedAt;
  }
  /**
   Attribute description last modified date
   */
  set lastModifiedAt(value: string) {
    this._lastModifiedAt = value;
  }
  /**
   The ID of the user that created the attribute description
   */
  get createdBy(): number | undefined {
    return this._createdBy;
  }
  /**
   The ID of the user that created the attribute description
   */
  set createdBy(value: number | undefined) {
    this._createdBy = value;
  }
  /**
   The ID of the user that last modified the attribute description
   */
  get lastModifiedBy(): number | undefined {
    return this._lastModifiedBy;
  }
  /**
   The ID of the user that last modified the attribute description
   */
  set lastModifiedBy(value: number | undefined) {
    this._lastModifiedBy = value;
  }
  /**
   The default value for this attribute
   */
  get defaultValue(): AttributeValue {
    return this._defaultValue;
  }
  /**
   The default value for this attribute
   */
  set defaultValue(value: AttributeValue) {
    this._defaultValue = value;
  }
}