mutation categoryUpdate($categoryId: Float!, $input: UpdateCategoryInput!, $categoryProductSearchInput: CategoryProductSearchInput, $language: String, $filterAvailableAttributeInput: FilterAvailableAttributeInput, $priceCalculateProductInput: PriceCalculateProductInput, $imageSearchFilters: MediaImageProductSearchInput, $imageVariantFilters: TransformationsInput!, $attributeResultSearchInput: AttributeResultSearchInput) {
  categoryUpdate(categoryId: $categoryId, input: $input) {
    ...CategoryFields
  }
}
