mutation categoryAddProductsClusters($id: Int!, $input: CategoryAddProductsClustersInput!, $categoryProductSearchInput: CategoryProductSearchInput, $language: String, $filterAvailableAttributeInput: FilterAvailableAttributeInput, $priceCalculateProductInput: PriceCalculateProductInput, $imageSearchFilters: MediaImageProductSearchInput, $imageVariantFilters: TransformationsInput!, $attributeResultSearchInput: AttributeResultSearchInput) {
  categoryAddProductsClusters(id: $id, input: $input) {
    ...CategoryAddProductsClustersResponseFields
  }
}
