mutation machineCreate($input: CreateSparePartsMachineInput!, $language: String, $sparePartsMachineProductSearchInput: SparePartsMachineProductSearchInput, $filterAvailableAttributeInput: FilterAvailableAttributeInput, $imageVariantFilters: TransformationsInput!, $priceCalculateProductInput: PriceCalculateProductInput, $imageSearchFilters: MediaImageProductSearchInput, $attributeResultSearchInput: AttributeResultSearchInput) {
  machineCreate(input: $input) {
    ...SparePartsMachineFields
  }
}
