mutation productSetDefaultCategory(
  $productId: Int!
  $categoryId: Int!
  $attributeResultSearchInput: AttributeResultSearchInput
  $priceCalculateProductInput: PriceCalculateProductInput
  $userBulkPriceProductInput: UserBulkPriceProductInput
  $imageSearchFilters: MediaImageProductSearchInput
  $language: String
  $imageVariantFilters: TransformationsInput!
  $mediaVideoSearchInput: MediaVideoProductSearchInput
  $mediaDocumentSearchInput: MediaDocumentProductSearchInput
) {
  productSetDefaultCategory(productId: $productId, categoryId: $categoryId) {
    ...ProductFields
  }
}
