mutation productAssignToCluster(
  $productId: Int!
  $clusterId: Int!
  $attributeResultSearchInput: AttributeResultSearchInput
  $priceCalculateProductInput: PriceCalculateProductInput
  $userBulkPriceProductInput: UserBulkPriceProductInput
  $imageSearchFilters: MediaImageProductSearchInput
  $language: String
  $imageVariantFilters: TransformationsInput!
  $mediaVideoSearchInput: MediaVideoProductSearchInput
  $mediaDocumentSearchInput: MediaDocumentProductSearchInput
) {
  productAssignToCluster(productId: $productId, clusterId: $clusterId) {
    ...ProductFields
  }
}
