import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The API Reference sidebar is generated by `docs/scripts/gen-api.js`
// (standalone TypeDoc + typedoc-docusaurus-theme) at
// docs/content/api/typedoc-sidebar.cjs. The standalone theme exports
// `{ items: [...] }` (Enumerations, Classes, Interfaces, Functions,
// Type-aliases). The file is gitignored and regenerated before every build,
// so it always exists at build time.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const typedocSidebar = require('./content/api/typedoc-sidebar.cjs');
const typedocItems = typedocSidebar.items ?? typedocSidebar;

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/build-a-frontend',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/client-config',
        'configuration/proxy-contract',
        'configuration/authentication',
        'configuration/cache-hints',
      ],
    },
    {
      type: 'category',
      label: 'Using the SDK',
      items: [
        'guides/services',
        'guides/operation-variables',
        'guides/direct-graphql',
        'guides/caching',
        'guides/error-handling',
        'guides/localized-fields',
        'guides/enums-and-serialization',
        'guides/legacy-apis',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/type-definitions', 'changelog'],
    },
    {
      type: 'category',
      label: 'History',
      collapsed: true,
      items: ['archive/migration-0.9.0', 'history/history'],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api/index'},
      items: typedocItems,
    },
  ],
};

export default sidebars;
